### ISSUE TITLE
Bug: Missing floating action bar

### ISSUE THREAD

**Issue by Aerex** [Limegrass/Wanicchou#15]
Really cool app. I downloaded the newest beta release on my Android device running stock Pie. I made a search but found no action bar. Also, I made sure to enable permissions to read write to the Anki database. 

Is it my device or something else?

**Comment by Limegrass** [comment]
@Aerex 
You meant the floating action button (FAB), correct? I couldn't reproduce the issue.
Do you not have AnkiDroid installed on your phone by any chance? It's set to not show the FAB without AnkiDroid installed. I believe at the time the AnkiDroid api didn't function without AnkiDroid installed. I haven't looked into if there's any way to interact with AnkiWeb recently.

If you actually mean the Actionbar for the list view in the Dev branch (overhaul), that hasn't yet made it into a release.

Unfortunately, I don't have a great logging system in place yet for errors.

I can throw some logging together quickly for the time being if you can confirm that you do have AnkiDroid installed. Otherwise I still plan to put off new development until the JLPT.

**Comment by Aerex** [comment]
Sorry about the late reply. I do have AnkiDroid installed. I am not sure why the app doesn't see anki droid installed. I will check the source code when I get the chance. Good luck on the jplt. I am guessing you are going for jplt 2

**Comment by Limegrass** [comment]
@Aerex I assume this issue still exists? I'll be reworking quite a bit of the implementation during this following week, and I'll keep a particular eye out for what's causing this to fail during that. I'd imagine it's related to the AnkiDroidHelper and it's interaction with the  AnkiDroid API that I didn't pay enough attention to when I first worked on this.

I'll be sure to test specifically with newer Android versions, and admittedly as I am writing this I realized I didn't test Pie through installing by the APK. Last time an APK related bug occurred, it was due to access modifiers being too restrictive.

I have the N2 and attempted the N1 this time around. I'm also sorry for the late reply, and thanks!

**Comment by Limegrass** [comment]
I've tried using the release APK along with generating new APKs, but I still can't seem to reproduce. I'll make sure my AnkiDroid api is up-to-date before next release, along with my rework. Hopefully some change would fix it.

**Comment by Aerex** [comment]
Great thanks for your work. Let me know if there is something I need to do at my end.

**Comment by Limegrass** [comment]
@Aerex A bit late in asking, but have you tried the newest version? It's only on the app store though. I haven't gotten around to getting FDroid to change things so it updates properly.

**Comment by Aerex** [comment]
I am getting the error `Failed to find provider info for com.ichi2.anki.flashcards`. Is there a specific version of AnkiDroid I need to be using? I am using version 2.8.4

**Comment by Limegrass** [comment]
There shouldn't be any dependency on the version of AnkiDroid you're using. Could you check to make sure that the AnkiDroid API is enabled in AnkiDroid's settings?
Settings -> Advanced -> Enable AnkiDroid API under the Plugins setting.

I'll add a properly crash log to the backlog for another release, I should be able to find time to work on it pretty soon as well. Sorry that this has gone on so long.

**Comment by Aerex** [comment]
It works! I didn't have the **Enable AnkiDroid API** checked.

 Thank you so much for keeping up with the issue. I would like to give a  donate if that is an option.

**Comment by Limegrass** [comment]
Not a problem! Sorry it took so long. I'll consider a donation option when the app is more fleshed out, but for something like this, I can't accept money.
